# Generated by Django 4.0.3 on 2022-06-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='impact',
            name='skills',
            field=models.ManyToManyField(to='character.skillownership'),
        ),
        migrations.AddField(
            model_name='impact',
            name='statistics',
            field=models.ManyToManyField(to='character.statisticownership'),
        ),
    ]
