# Generated by Django 4.0.5 on 2022-06-18 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('character', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='character',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.profession'),
        ),
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.race'),
        ),
        migrations.AddField(
            model_name='character',
            name='skills',
            field=models.ManyToManyField(related_name='characters', through='character.SkillOwnership', to='character.skill'),
        ),
        migrations.AddField(
            model_name='character',
            name='statistics',
            field=models.ManyToManyField(related_name='characters', through='character.StatisticOwnership', to='character.statistic'),
        ),
        migrations.AddField(
            model_name='character',
            name='tool_kits',
            field=models.ManyToManyField(related_name='characters', through='character.ToolKitOwnership', to='character.toolkit'),
        ),
        migrations.AddField(
            model_name='character',
            name='weapons',
            field=models.ManyToManyField(related_name='characters', through='character.WeaponOwnership', to='character.weapon'),
        ),
        migrations.AddField(
            model_name='armorownership',
            name='armor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.armor'),
        ),
        migrations.AddField(
            model_name='armorownership',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.character'),
        ),
        migrations.AddField(
            model_name='armor',
            name='effects',
            field=models.ManyToManyField(to='character.effect'),
        ),
    ]
