# Generated by Django 4.0.3 on 2022-07-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_remove_languageownership_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='impact',
            name='label',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
