# Generated by Django 4.0.3 on 2022-07-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0005_race_region_standings"),
    ]

    operations = [
        migrations.AddField(
            model_name="impact",
            name="stopping_power",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
