# Generated by Django 4.0.3 on 2022-07-10 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0007_alter_impact_label'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='regionstanding',
            unique_together={('region', 'social_standing')},
        ),
    ]
