# Generated by Django 4.0.3 on 2022-07-10 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0008_alter_regionstanding_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='country',
            unique_together={('label', 'region')},
        ),
    ]
