# Generated by Django 4.0.3 on 2022-07-11 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0009_alter_country_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enemy',
            name='linked_character',
        ),
        migrations.RemoveField(
            model_name='enemy',
            name='othercharactermixin_ptr',
        ),
        migrations.RemoveField(
            model_name='enemy',
            name='player_character',
        ),
        migrations.RemoveField(
            model_name='familystatus',
            name='impacts',
        ),
        migrations.RemoveField(
            model_name='lifeevent',
            name='impacts',
        ),
        migrations.RemoveField(
            model_name='mostinfluencialfriend',
            name='impacts',
        ),
        migrations.RemoveField(
            model_name='mostinfluencialfriend',
            name='linked_character',
        ),
        migrations.RemoveField(
            model_name='mostinfluencialfriend',
            name='othercharactermixin_ptr',
        ),
        migrations.RemoveField(
            model_name='mostinfluencialfriend',
            name='player_character',
        ),
        migrations.RemoveField(
            model_name='romance',
            name='linked_character',
        ),
        migrations.RemoveField(
            model_name='romance',
            name='othercharactermixin_ptr',
        ),
        migrations.RemoveField(
            model_name='romance',
            name='player_character',
        ),
        migrations.RemoveField(
            model_name='sibling',
            name='linked_character',
        ),
        migrations.RemoveField(
            model_name='sibling',
            name='othercharactermixin_ptr',
        ),
        migrations.RemoveField(
            model_name='sibling',
            name='player_character',
        ),
        migrations.RemoveField(
            model_name='character',
            name='family_status',
        ),
        migrations.RemoveField(
            model_name='character',
            name='fate_event',
        ),
        migrations.RemoveField(
            model_name='character',
            name='life_events',
        ),
        migrations.DeleteModel(
            name='Ally',
        ),
        migrations.DeleteModel(
            name='Enemy',
        ),
        migrations.DeleteModel(
            name='FamilyStatus',
        ),
        migrations.DeleteModel(
            name='FateEvent',
        ),
        migrations.DeleteModel(
            name='LifeEvent',
        ),
        migrations.DeleteModel(
            name='MostInfluencialFriend',
        ),
        migrations.DeleteModel(
            name='OtherCharacterMixin',
        ),
        migrations.DeleteModel(
            name='Romance',
        ),
        migrations.DeleteModel(
            name='Sibling',
        ),
    ]
