# Generated by Django 4.0.5 on 2022-07-12 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0011_fateevent_othercharactermixin_lifeevent_familystatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilltreeitem',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.profession'),
        ),
    ]
