# Generated by Django 4.0.3 on 2022-07-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0016_alter_weapon_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicerollinformation',
            name='modifier',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='dicerollinformation',
            unique_together={('number_of_dice', 'number_of_sides', 'modifier')},
        ),
    ]
