# Generated by Django 4.0.3 on 2022-07-13 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0017_alter_dicerollinformation_modifier_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dicerollinformation',
            options={'ordering': ('number_of_sides', 'number_of_dice', 'modifier')},
        ),
    ]
