# Generated by Django 4.0.3 on 2022-07-13 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0020_alter_rangeinformation_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="effectownership",
            old_name="effet",
            new_name="effect",
        ),
    ]
