# Generated by Django 4.0.3 on 2022-07-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "character",
            "0022_alter_alchemicalitem_label_alter_ammunition_label_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="armor",
            name="reliability",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
