# Generated by Django 4.0.3 on 2022-07-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0023_alter_armor_reliability'),
    ]

    operations = [
        migrations.AddField(
            model_name='armor',
            name='armor_type',
            field=models.CharField(choices=[('light', 'Light'), ('medium', 'Medium'), ('heavy', 'Heavy')], default='light', max_length=50),
        ),
    ]
