# Generated by Django 4.0.3 on 2022-07-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0024_armor_armor_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armor',
            name='reliability',
        ),
        migrations.CreateModel(
            name='Shield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(null=True)),
                ('weight', models.FloatField()),
                ('price', models.IntegerField(help_text='Price in Redanian crowns')),
                ('category', models.CharField(choices=[('head_armor', 'Head Armor'), ('torso_armor', 'Torso Armor'), ('leg_armor', 'Leg Armor'), ('shields', 'Shields')], max_length=50)),
                ('armor_type', models.CharField(choices=[('light', 'Light'), ('medium', 'Medium'), ('heavy', 'Heavy')], default='light', max_length=50)),
                ('availablility', models.CharField(choices=[('E', 'Everywhere'), ('C', 'Common'), ('P', 'Poor'), ('R', 'Rare')], max_length=1)),
                ('reliability', models.IntegerField()),
                ('enhancement_spots', models.IntegerField(default=0)),
                ('encombrance_value', models.IntegerField(default=0)),
                ('is_elder', models.BooleanField(default=False)),
                ('effects', models.ManyToManyField(blank=True, to='character.effectownership')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
