# Generated by Django 4.0.3 on 2022-07-16 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0032_alter_gear_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impact',
            name='label',
        ),
        migrations.CreateModel(
            name='WeaponOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.weapon')),
            ],
        ),
        migrations.CreateModel(
            name='ToolKitOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.toolkit')),
            ],
        ),
        migrations.CreateModel(
            name='ShieldOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enhancements', models.ManyToManyField(blank=True, to='character.armorenhancement')),
                ('shield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.shield')),
            ],
        ),
        migrations.CreateModel(
            name='GearOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('gear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.gear')),
            ],
        ),
        migrations.CreateModel(
            name='ArmorOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('armor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.armor')),
                ('enhancements', models.ManyToManyField(blank=True, to='character.armorenhancement')),
            ],
        ),
        migrations.CreateModel(
            name='AmmunitionOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('ammunition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.ammunition')),
            ],
        ),
        migrations.AlterField(
            model_name='character',
            name='armor',
            field=models.ManyToManyField(blank=True, related_name='characters', to='character.shieldownership'),
        ),
        migrations.AlterField(
            model_name='character',
            name='weapons',
            field=models.ManyToManyField(blank=True, related_name='characters', to='character.weaponownership'),
        ),
    ]
