# Generated by Django 4.0.3 on 2022-07-16 13:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0033_remove_impact_label_weaponownership_toolkitownership_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='improvement_points',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='impact',
            name='ammunition',
            field=models.ManyToManyField(blank=True, to='character.ammunitionownership'),
        ),
        migrations.AddField(
            model_name='impact',
            name='armor',
            field=models.ManyToManyField(blank=True, to='character.armorownership'),
        ),
        migrations.AddField(
            model_name='impact',
            name='gear',
            field=models.ManyToManyField(blank=True, to='character.gearownership'),
        ),
        migrations.AddField(
            model_name='impact',
            name='shield',
            field=models.ManyToManyField(blank=True, to='character.shieldownership'),
        ),
        migrations.AddField(
            model_name='impact',
            name='tool_kits',
            field=models.ManyToManyField(blank=True, to='character.toolkitownership'),
        ),
        migrations.AddField(
            model_name='impact',
            name='weapon',
            field=models.ManyToManyField(blank=True, to='character.weaponownership'),
        ),
        migrations.AddField(
            model_name='skillownership',
            name='condition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='statisticownership',
            name='condition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='alchemicalitem',
            name='price',
            field=models.PositiveIntegerField(help_text='Price in Redanian crowns'),
        ),
        migrations.AlterField(
            model_name='ammunition',
            name='base_quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ammunition',
            name='price',
            field=models.PositiveIntegerField(help_text='Price in Redanian crowns'),
        ),
        migrations.AlterField(
            model_name='ammunition',
            name='reliability',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ammunitionownership',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='armor',
            name='encombrance_value',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='armor',
            name='enhancement_spots',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='armor',
            name='price',
            field=models.PositiveIntegerField(help_text='Price in Redanian crowns'),
        ),
        migrations.AlterField(
            model_name='armorenhancement',
            name='price',
            field=models.PositiveIntegerField(help_text='Price in Redanian crowns'),
        ),
        migrations.AlterField(
            model_name='character',
            name='ammunition',
            field=models.ManyToManyField(blank=True, related_name='characters', to='character.ammunitionownership'),
        ),
        migrations.AlterField(
            model_name='character',
            name='gear',
            field=models.ManyToManyField(blank=True, related_name='characters', to='character.gearownership'),
        ),
        migrations.AlterField(
            model_name='character',
            name='tool_kits',
            field=models.ManyToManyField(blank=True, related_name='characters', to='character.toolkitownership'),
        ),
        migrations.AlterField(
            model_name='dicerollinformation',
            name='modifier',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dicerollinformation',
            name='number_of_dice',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='dicerollinformation',
            name='number_of_sides',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='power_value',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='gear',
            name='base_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gear',
            name='price',
            field=models.PositiveIntegerField(help_text='Price in Redanian crowns'),
        ),
        migrations.AlterField(
            model_name='gearownership',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='othercharactermixin',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='profession',
            name='starting_low_danger_hexes',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='profession',
            name='starting_novice_invocations',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='profession',
            name='starting_novice_rituals',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='profession',
            name='starting_novice_spells',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='profession',
            name='starting_vigor',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='rangeinformation',
            name='body_multiplier',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rangeinformation',
            name='definitive_value',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shield',
            name='encombrance_value',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shield',
            name='enhancement_spots',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shield',
            name='price',
            field=models.PositiveIntegerField(help_text='Price in Redanian crowns'),
        ),
        migrations.AlterField(
            model_name='shield',
            name='reliability',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='skilltreeitem',
            name='depth',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='skilltreeitemownership',
            name='value',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='toolkit',
            name='price',
            field=models.PositiveIntegerField(help_text='Price in Redanian crowns'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='enhancement_spots',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='hands_required',
            field=models.PositiveIntegerField(choices=[(1, 'One-handed'), (2, 'Two-handed')]),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='price',
            field=models.PositiveIntegerField(help_text='Price in Redanian crowns'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='reliability',
            field=models.PositiveIntegerField(),
        ),
    ]
