# Generated by Django 4.0.3 on 2022-07-19 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0036_character_shield_alter_character_armor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ally',
            name='linked_character',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='is_ally', to='character.character'),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='linked_character',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='is_enemy', to='character.character'),
        ),
        migrations.AlterField(
            model_name='mostinfluencialfriend',
            name='linked_character',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='is_most_influencial_friend', to='character.character'),
        ),
        migrations.AlterField(
            model_name='romance',
            name='linked_character',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='is_romance', to='character.character'),
        ),
        migrations.AlterField(
            model_name='sibling',
            name='linked_character',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='is_sibling', to='character.character'),
        ),
    ]
