# Generated by Django 4.0.3 on 2022-07-19 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0037_alter_ally_linked_character_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='characters', to='character.languageownership'),
        ),
    ]
