# Generated by Django 4.0.3 on 2022-07-19 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0038_alter_character_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='characters', to='character.skillownership'),
        ),
        migrations.AlterField(
            model_name='character',
            name='statistics',
            field=models.ManyToManyField(blank=True, related_name='characters', to='character.statisticownership'),
        ),
    ]
