# Generated by Django 4.0.3 on 2022-07-19 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0039_alter_character_skills_alter_character_statistics'),
    ]

    operations = [
    ]
