# Generated by Django 4.0.3 on 2022-07-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0040_remove_character_statistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='statistics',
            field=models.ManyToManyField(blank=True, related_name='characters', to='character.statisticownership'),
        ),
    ]
