# Generated by Django 4.0.3 on 2022-07-19 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0042_remove_character_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='characters', to='character.skillownership'),
        ),
    ]
