# Generated by Django 4.0.3 on 2022-07-19 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0043_character_skills'),
    ]

    operations = [
    ]
