# Generated by Django 4.0.3 on 2022-07-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0044_remove_character_skill_tree_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='skill_tree_items',
            field=models.ManyToManyField(blank=True, related_name='characters', to='character.skilltreeitemownership'),
        ),
    ]
