# Generated by Django 4.0.3 on 2022-07-19 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0045_character_skill_tree_items'),
    ]

    operations = [
    ]
