# Generated by Django 4.0.3 on 2022-07-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0046_remove_character_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='characters', to='character.languageownership'),
        ),
    ]
