# Generated by Django 4.0.3 on 2022-07-21 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0047_character_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='affectations',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='clothing',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='family_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='character.familystatus'),
        ),
        migrations.AlterField(
            model_name='character',
            name='fate_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='character.fateevent'),
        ),
        migrations.AlterField(
            model_name='character',
            name='feelings_on_people',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='hair_style',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='improvement_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='most_influencial_friend',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.mostinfluencialfriend'),
        ),
        migrations.AlterField(
            model_name='character',
            name='personality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='values_person',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
