# Generated by Django 4.0.3 on 2022-07-30 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0048_alter_character_affectations_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('region', 'label'), 'verbose_name_plural': 'countries'},
        ),
    ]
